"""making sector name unique

Revision ID: 717a67183018
Revises: 03f73746cf57
Create Date: 2023-06-24 18:43:32.670802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '717a67183018'
down_revision = '03f73746cf57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sector', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sector', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
